- id: '1703098072400'
  alias: TRV Calibrator Bedroom
  description: ''
  use_blueprint:
    path: rotilho/trv_calibrator.yaml
    input:
      trv: climate.radiator_bedroom
      temperature_sensor: sensor.temperature_bedroom_temperature
      trv_calibration_number: number.radiator_bedroom_local_temperature_calibration
- id: '1703156526754'
  alias: TRV Calibrator Office
  description: ''
  use_blueprint:
    path: rotilho/trv_calibrator.yaml
    input:
      trv: climate.radiator_office
      temperature_sensor: sensor.temperature_office_temperature
      trv_calibration_number: number.radiator_office_local_temperature_calibration
- id: '1703323733462'
  alias: Light bulb restore on turned on in Office
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.light_switch_office
    from: 'off'
    to: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: light.light_bulb_office
          state: 'off'
        - condition: state
          entity_id: light.light_bulb_office
          state: unknown
        - condition: state
          entity_id: light.light_bulb_office
          state: unavailable
      sequence:
      - type: turn_on
        device_id: 61b83c69693b8014d4924c78d8d76a60
        entity_id: 84f3bab49846227acf98ac355ed36c74
        domain: light
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.is_night_mode
          state: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.light_bulb_office
        data:
          brightness: 60
          transition: 0
          rgb_color:
          - 116
          - 74
          - 1
    default:
    - service: light.turn_on
      target:
        entity_id: light.light_bulb_office
      data:
        transition: 1
        color_temp: 500
        brightness: 130
  mode: restart
- id: '1703499610744'
  alias: Light Switch Door Way Sync Left to Right
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
    entity_id: 9d70b4baef8bbfea6a441531d4206d67
    domain: switch
  condition: []
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: device
          type: is_on
          device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
          entity_id: 9d70b4baef8bbfea6a441531d4206d67
          domain: switch
        - condition: device
          type: is_off
          device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
          entity_id: 63fc81cf2189c83c764c73fda29bfac2
          domain: switch
      sequence:
      - type: turn_on
        device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
        entity_id: 63fc81cf2189c83c764c73fda29bfac2
        domain: switch
    - conditions:
      - condition: and
        conditions:
        - condition: device
          type: is_off
          device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
          entity_id: 9d70b4baef8bbfea6a441531d4206d67
          domain: switch
        - condition: device
          type: is_on
          device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
          entity_id: 63fc81cf2189c83c764c73fda29bfac2
          domain: switch
      sequence:
      - type: turn_off
        device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
        entity_id: 63fc81cf2189c83c764c73fda29bfac2
        domain: switch
  mode: restart
- id: '1703506200819'
  alias: Scene TV On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - remote.android_tv
    from:
    to: 'on'
  condition: []
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.is_tv_mode
    data: {}
  - if:
    - condition: time
      after: '16:00:00'
    then:
    - service: script.tv_scene
      data: {}
  mode: restart
- id: '1703506966884'
  alias: Scene TV Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.android_tv_2
    from:
    to: unavailable
  condition:
  - condition: state
    entity_id: input_boolean.is_scene_enabled_tv_mode
    state: 'on'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.is_tv_mode
    data: {}
  - service: script.default_scene
    data: {}
  mode: restart
- id: '1703509721556'
  alias: Power Plug 1Turn on at 16:00
  description: ''
  trigger:
  - platform: time_pattern
    hours: '16'
  condition:
  - condition: state
    entity_id: input_boolean.is_out_of_home
    state: 'off'
  action:
  - type: turn_on
    device_id: fd4f21f6ddec80b91491cb78d79dc226
    entity_id: 1d297051e94c6d96d37e3481605a0d68
    domain: switch
  - type: turn_on
    device_id: 3ba9465ebaf8aaf5f833451f6b306084
    entity_id: be144f8430257286916aed6cee7b4832
    domain: switch
  mode: restart
- id: '1703514397437'
  alias: Scene Night On
  description: ''
  trigger:
  - platform: time
    at: 01:30:00
  - platform: state
    entity_id:
    - binary_sensor.alex_phone_is_charging
    from:
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: input_datetime.time_for_night_mode_on
      before: 08:00:00
    - condition: state
      entity_id: input_boolean.is_night_mode
      state: 'off'
    - condition: state
      entity_id: input_boolean.is_out_of_home
      state: 'off'
  action:
  - service: light.turn_on
    metadata: {}
    data:
      color_temp: 500
      brightness_pct: 1
    target:
      entity_id:
      - light.light_bulb_bedroom_both
  - service: script.night_scene_script
    data: {}
  mode: single
- id: '1703517954260'
  alias: Scene Night Off
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition:
  - condition: state
    entity_id: input_boolean.is_scene_enabled_night_mode
    state: 'on'
  action:
  - service: homeassistant.turn_off
    target:
      entity_id: input_boolean.is_night_mode
    data: {}
  mode: restart
- id: '1703532855855'
  alias: TRV Calibrator Living Room
  description: ''
  use_blueprint:
    path: rotilho/trv_calibrator.yaml
    input:
      trv: climate.radiator_living_room
      temperature_sensor: sensor.temperature_living_room_temperature
      trv_calibration_number: number.radiator_living_room_local_temperature_calibration
- id: '1703533961152'
  alias: Scene Out of Home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.alex_phone
    from: home
    to: not_home
  - platform: state
    entity_id:
    - device_tracker.lena_phone
    from: home
    to: not_home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.alex_phone
      state: not_home
    - condition: state
      entity_id: device_tracker.lena_phone
      state: not_home
    - condition: state
      entity_id: input_boolean.is_scene_enabled_out_of_home
      state: 'on'
  action:
  - service: script.out_of_home_scene
    data: {}
  mode: restart
- id: '1703534667532'
  alias: Scene Come Back Home
  description: ''
  trigger:
  - platform: device
    device_id: 4491a48c7d623f8065437eb7b0ca2705
    domain: lock
    entity_id: 71b9065df4bf5c398d2b19e2cfe666f7
    type: unlocked
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.is_out_of_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.is_scene_enabled_out_of_home
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.alex_phone
        state: home
      - condition: state
        entity_id: device_tracker.lena_phone
        state: home
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.is_out_of_home
    data: {}
  - service: script.default_scene
    data: {}
  - type: turn_on
    device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
    entity_id: 63fc81cf2189c83c764c73fda29bfac2
    domain: switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
    entity_id: 63fc81cf2189c83c764c73fda29bfac2
    domain: switch
  mode: restart
- id: '1703586558948'
  alias: Light bulb restore on turned on in Kitchen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.light_switch_kitchen
    from: 'off'
    to: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: light.light_bulb_kitchen
          state: 'off'
        - condition: state
          entity_id: light.light_bulb_kitchen
          state: unknown
        - condition: state
          entity_id: light.light_bulb_kitchen
          state: unavailable
      sequence:
      - type: turn_on
        device_id: 71f5d3918bce9ed4109a151edd75457e
        entity_id: 4ece1e3e7fbb975c242f0049e291aa96
        domain: switch
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.is_night_mode
          state: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id:
          - light.light_bulb_kitchen
        data:
          brightness: 60
          transition: 0
          rgb_color:
          - 116
          - 74
          - 1
    default:
    - service: light.turn_on
      target:
        entity_id:
        - light.light_bulb_kitchen
      data:
        transition: 1
        color_temp: 500
        brightness: 130
  mode: single
- id: '1703586698215'
  alias: Light bulb restore on turned on in Living Room
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.light_switch_living_room_right
    from: 'off'
    to: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: light.light_bulb_living_room
          state: 'off'
        - condition: state
          entity_id: light.light_bulb_living_room
          state: unknown
        - condition: state
          entity_id: light.light_bulb_living_room
          state: unavailable
      sequence:
      - type: turn_on
        device_id: 5194faa91def9215b7d5fb5c79fbe422
        entity_id: 4fd11c35a6fea97277a0b8a420f15f99
        domain: switch
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.is_night_mode
          state: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id:
          - light.light_bulb_living_room
        data:
          brightness: 60
          transition: 0
          rgb_color:
          - 116
          - 74
          - 1
    default:
    - service: light.turn_on
      target:
        entity_id:
        - light.light_bulb_living_room
      data:
        transition: 1
        color_temp: 500
        brightness: 130
  mode: restart
- id: '1703950084431'
  alias: Light Switch Toilet Turn On Fun
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.temperature_toilet_humidity
    for:
      hours: 0
      minutes: 30
      seconds: 0
    above: 70
  condition:
  - condition: state
    entity_id: switch.light_switch_toilet_right
    state: 'off'
  action:
  - type: turn_on
    device_id: 76a8d32746327843cc4e2ec948563958
    entity_id: b2d128e4857598ba79e025578b6e3bfe
    domain: switch
  mode: single
- id: '1703953317779'
  alias: Light Switch Toilet Turn Off Fun
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.temperature_toilet_humidity
    for:
      hours: 0
      minutes: 0
      seconds: 30
    below: 70
  condition:
  - condition: state
    entity_id: switch.light_switch_toilet_right
    state: 'on'
  action:
  - type: turn_off
    device_id: 76a8d32746327843cc4e2ec948563958
    entity_id: b2d128e4857598ba79e025578b6e3bfe
    domain: switch
  mode: single
- id: '1704045559369'
  alias: Light Switch Turn Light When Door is Opened
  description: ''
  trigger:
  - platform: device
    device_id: 4491a48c7d623f8065437eb7b0ca2705
    domain: lock
    entity_id: 71b9065df4bf5c398d2b19e2cfe666f7
    type: unlocked
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.is_out_of_home
      state: 'off'
    - condition: state
      entity_id: switch.light_switch_door_way_right
      state: 'off'
  action:
  - type: turn_on
    device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
    entity_id: 63fc81cf2189c83c764c73fda29bfac2
    domain: switch
  - delay:
      hours: 0
      minutes: 3
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
    entity_id: 63fc81cf2189c83c764c73fda29bfac2
    domain: switch
  mode: single
- id: '1704097005310'
  alias: Light Switch Door Way Sync Right to Left
  description: ''
  trigger:
  - platform: device
    type: turned_off
    device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
    entity_id: 63fc81cf2189c83c764c73fda29bfac2
    domain: switch
  condition:
  - condition: device
    type: is_on
    device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
    entity_id: 9d70b4baef8bbfea6a441531d4206d67
    domain: switch
  action:
  - type: turn_off
    device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
    entity_id: 9d70b4baef8bbfea6a441531d4206d67
    domain: switch
  mode: single
