- id: '1703098072400'
  alias: TRV Calibrator Bedroom
  description: ''
  use_blueprint:
    path: rotilho/trv_calibrator.yaml
    input:
      trv: climate.radiator_bedroom
      temperature_sensor: sensor.temperature_bedroom_temperature
      trv_calibration_number: number.radiator_bedroom_local_temperature_calibration
- id: '1703156526754'
  alias: TRV Calibrator Office
  description: ''
  use_blueprint:
    path: rotilho/trv_calibrator.yaml
    input:
      trv: climate.radiator_office
      temperature_sensor: sensor.temperature_office_temperature
      trv_calibration_number: number.radiator_office_local_temperature_calibration
- id: '1703323733462'
  alias: Light bulb restore on turned on in Office
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.light_switch_office
    from: 'off'
    to: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: light.light_office
          state: 'off'
        - condition: state
          entity_id: light.light_office
          state: unknown
        - condition: state
          entity_id: light.light_office
          state: unavailable
      sequence:
      - type: turn_on
        device_id: 61b83c69693b8014d4924c78d8d76a60
        entity_id: 2b46d7d2c8aeb8981640add088abc223
        domain: light
        brightness_pct: 1
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.is_night_mode
          state: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id: light.light_office
        data:
          brightness: 60
          transition: 0
          rgb_color:
          - 116
          - 74
          - 1
    default:
    - service: light.turn_on
      target:
        entity_id: light.light_office
      data:
        transition: 1
        color_temp: 500
        brightness: 130
  mode: restart
- id: '1703499610744'
  alias: Door Way sync two buttons left to right
  description: ''
  trigger:
  - platform: device
    type: changed_states
    device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
    entity_id: b9696d7957547e1d5021cadb61a4cde2
    domain: switch
  condition: []
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: device
          type: is_on
          device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
          entity_id: b9696d7957547e1d5021cadb61a4cde2
          domain: switch
        - condition: device
          type: is_off
          device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
          entity_id: b73c699ba20e6b7efd6685f510c11879
          domain: switch
      sequence:
      - type: turn_on
        device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
        entity_id: b73c699ba20e6b7efd6685f510c11879
        domain: switch
    - conditions:
      - condition: and
        conditions:
        - condition: device
          type: is_off
          device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
          entity_id: b9696d7957547e1d5021cadb61a4cde2
          domain: switch
        - condition: device
          type: is_on
          device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
          entity_id: b73c699ba20e6b7efd6685f510c11879
          domain: switch
      sequence:
      - type: turn_off
        device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
        entity_id: b73c699ba20e6b7efd6685f510c11879
        domain: switch
  mode: restart
- id: '1703503884465'
  alias: Light bulb restore on turned on in Bedroom
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 4e53e381628e10ad30c5bcde381b7d81
    entity_id: 88cb1f3ca7233ba5749b3098c84241a9
    domain: light
    for:
      hours: 0
      minutes: 0
      seconds: 1
  condition: []
  action:
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: sun.sun
          state: below_horizon
        - condition: state
          entity_id: input_boolean.is_night_mode
          state: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id:
          - light.bedroom_lights
        data:
          brightness: 60
          transition: 0
          rgb_color:
          - 116
          - 74
          - 1
    default:
    - service: light.turn_on
      target:
        entity_id:
        - light.bedroom_lights
      data:
        transition: 1
        color_temp: 500
        brightness: 130
  mode: restart
- id: '1703506200819'
  alias: Scene TV On
  description: ''
  trigger:
  - platform: state
    entity_id:
    - remote.android_tv
    from:
    to: 'on'
  condition: []
  action:
  - service: script.tv_scene
    data: {}
  mode: restart
- id: '1703506966884'
  alias: Scene TV Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.android_tv_2
    from:
    to: unavailable
  condition:
  - condition: state
    entity_id: input_boolean.is_scene_enabled_tv_mode
    state: 'on'
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.guest_scene
    metadata: {}
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.is_tv_mode
    data: {}
  mode: restart
- id: '1703509721556'
  alias: Power Plug 1Turn on at 16:00
  description: ''
  trigger:
  - platform: time_pattern
    hours: '16'
  condition:
  - condition: state
    entity_id: input_boolean.is_out_of_home
    state: 'off'
  action:
  - type: turn_on
    device_id: fd4f21f6ddec80b91491cb78d79dc226
    entity_id: 190bb6c68ec5cbcf11fc16c177e0b1d0
    domain: switch
  - type: turn_on
    device_id: 3ba9465ebaf8aaf5f833451f6b306084
    entity_id: c52b449cae2014cbd57242fb73e3b77a
    domain: switch
  mode: restart
- id: '1703514397437'
  alias: Scene Night On
  description: ''
  trigger:
  - platform: time
    at: 01:30:00
  - platform: state
    entity_id:
    - binary_sensor.alex_phone_is_charging
    from:
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: input_datetime.time_for_night_mode_on
      before: 08:00:00
    - condition: state
      entity_id: input_boolean.is_night_mode
      state: 'off'
  action:
  - service: script.night_scene_script
    data: {}
  mode: single
- id: '1703517954260'
  alias: Scene Night Off
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition:
  - condition: state
    entity_id: input_boolean.is_scene_enabled_night_mode
    state: 'on'
  action:
  - service: homeassistant.turn_off
    target:
      entity_id: input_boolean.is_night_mode
    data: {}
  mode: restart
- id: '1703532855855'
  alias: TRV Calibrator Living Room
  description: ''
  use_blueprint:
    path: rotilho/trv_calibrator.yaml
    input:
      trv: climate.radiator_living_room
      temperature_sensor: sensor.temperature_living_room_temperature
      trv_calibration_number: number.radiator_living_room_local_temperature_calibration
- id: '1703533961152'
  alias: Scene Out of Home
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.alex_phone
    from: home
    to: not_home
  - platform: state
    entity_id:
    - device_tracker.lena_phone
    from: home
    to: not_home
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.alex_phone
      state: not_home
    - condition: state
      entity_id: device_tracker.lena_phone
      state: not_home
  action:
  - service: script.out_of_home_scene
    data: {}
  mode: restart
- id: '1703534667532'
  alias: Scene Come Back Home
  description: ''
  trigger:
  - platform: device
    device_id: 4491a48c7d623f8065437eb7b0ca2705
    domain: lock
    entity_id: 71b9065df4bf5c398d2b19e2cfe666f7
    type: unlocked
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.is_out_of_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.is_scene_enabled_out_of_home
      state: 'on'
    - condition: or
      conditions:
      - condition: state
        entity_id: device_tracker.alex_phone
        state: home
      - condition: state
        entity_id: device_tracker.lena_phone
        state: home
  action:
  - service: homeassistant.turn_off
    target:
      entity_id: input_boolean.is_out_of_home
    data: {}
  - service: script.default_scene
    data: {}
  - type: turn_on
    device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
    entity_id: b73c699ba20e6b7efd6685f510c11879
    domain: switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 30
      milliseconds: 0
  - type: turn_off
    device_id: 7b9ef4e1b57fd30160f9287a3d9ff8b4
    entity_id: b73c699ba20e6b7efd6685f510c11879
    domain: switch
  mode: restart
- id: '1703586558948'
  alias: Light bulb restore on turned on in Kitchen
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.light_switch_kitchen
    from: 'off'
    to: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: light.light_kitchen
          state: 'off'
        - condition: state
          entity_id: light.light_kitchen
          state: unknown
        - condition: state
          entity_id: light.light_kitchen
          state: unavailable
      sequence:
      - type: turn_on
        device_id: 71f5d3918bce9ed4109a151edd75457e
        entity_id: 463e6d64bff6bdc80b849faa2e975904
        domain: switch
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.is_night_mode
          state: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id:
          - light.light_kitchen
        data:
          brightness: 60
          transition: 0
          rgb_color:
          - 116
          - 74
          - 1
    default:
    - service: light.turn_on
      target:
        entity_id:
        - light.light_kitchen
      data:
        transition: 1
        color_temp: 500
        brightness: 130
  mode: single
- id: '1703586698215'
  alias: Light bulb restore on turned on in Living Room
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.light_switch_living_room_right
    from: 'off'
    to: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 100
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: state
          entity_id: light.light_living_room
          state: 'off'
        - condition: state
          entity_id: light.light_living_room
          state: unknown
        - condition: state
          entity_id: light.light_living_room
          state: unavailable
      sequence:
      - type: turn_on
        device_id: 5194faa91def9215b7d5fb5c79fbe422
        entity_id: e61a8091e3b55f1b77b1eac83f33fc17
        domain: switch
  - choose:
    - conditions:
      - condition: and
        conditions:
        - condition: state
          entity_id: input_boolean.is_night_mode
          state: 'on'
      sequence:
      - service: light.turn_on
        target:
          entity_id:
          - light.light_living_room
        data:
          brightness: 60
          transition: 0
          rgb_color:
          - 116
          - 74
          - 1
    default:
    - service: light.turn_on
      target:
        entity_id:
        - light.light_living_room
      data:
        transition: 1
        color_temp: 500
        brightness: 130
  mode: restart
