homeassistant:
  packages: !include_dir_merge_named packages

default_config:

frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

panel_custom:
  - name: server_state
    sidebar_title: "System"
    sidebar_icon: mdi:server
    js_url: /api/hassio/app/entrypoint.js
    url_path: "hassio/system"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

http:
  ip_ban_enabled: true
  login_attempts_threshold: 10
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.86.0/24
    - 172.30.232.0/24
    - 172.30.32.0/24

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/my-cards/my-cards.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/simple-weather-card/simple-weather-card-bundle.js
      type: module
