- platform: template
  sensors:
    count_lights_on:
      friendly_name: "Total Lights Count"
      icon_template: mdi:lightbulb
      value_template: >
        {{ [
            states('switch.light_switch_doorway_left') == 'on',
            states('switch.light_switch_doorway_right') == 'on',
            states('switch.light_switch_boiler_room') == 'on',
            states('switch.light_switch_corridor') == 'on',
            states('switch.light_switch_living_room_center') == 'on',
            states('switch.light_switch_living_room_left') == 'on',
            states('switch.light_switch_living_room_right') == 'on',
            states('switch.light_switch_kitchen') == 'on',
            states('switch.light_switch_toilet_right') == 'on',
            states('switch.light_switch_office') == 'on',
            states('switch.light_switch_playroom') == 'on',
            states('switch.light_switch_bedroom') == 'on',
            states('switch.light_switch_garage') == 'on'
          ] | select('==', true) | list | count }}
